# Site settings
title: Parkers Code
header-img: img/home-bg.png
email: park.thompson@gmail.com
copyright_name: parkerray
description: > # this means to ignore newlines until "baseurl:"
  Blogging about my experiences in code and my quest for excellence.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: parkerthompson_
github_username:  parkerray
learn_profile: parkerray
email_username: park.thompson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
